title: 首页
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: 希望工作室长期招新

  # - tag: list
  #   header: false
  #   content:
  #     - text: 招新详情
  #       url: page?path=other/hope-studio/invite

  - tag: list
    header: 使用必读
    content:
      - text: 小程序使用须知
        icon: about
        url: page?path=other/about/guide

  - tag: grid
    header: 您可能想关注
    content:
      - text: 录取查询
        color: orange
        name: Search
        icon: search
        path: intro/enroll/search

      - text: 每日健康上报
        color: purple
        name: Report
        icon: apply
        path: guide/prepare/epidemic/miniprogram

      - text: 新生入学教育
        color: blue
        name: Course
        icon: study
        path: guide/prepare/yiban/

      - text: 专业介绍
        color: red
        name: Major
        icon: about
        path: intro/school/major

      - text: 学校介绍
        color: mauve
        name: Intro
        icon: about
        path: intro/about/

      - text: 转专业
        color: red
        name: Change Major
        icon: change
        path: guide/change-major/

      - text: 学位
        color: blue
        name: Degree
        icon: degree
        path: guide/degree/

      - text: 新生群
        color: red
        name: QQ Group
        icon: qq-group
        path: guide/prepare/qq-group/

      - text: 寝室
        color: grey
        name: Dorm
        icon: dorm
        path: guide/dorm/

      - text: 食堂
        color: mauve
        name: Dining
        icon: dining
        path: guide/dining/

      - text: 入学准备
        color: red
        name: Prepare
        icon: prepare
        path: guide/prepare/

      - text: 谨防诈骗
        color: blue
        name: Protection
        icon: alert
        path: guide/prepare/cheat

    footer: 更多内容请详见下方其他 Tab 页
