title: é¦–é¡µ
id: main
grey: true
hidden: true
content:
  # - tag: title
  #   text: å¸Œæœ›å·¥ä½œå®¤é•¿æœŸæ‹›æ–°

  # - tag: list
  #   header: false
  #   content:
  #     - text: æ‹›æ–°è¯¦æƒ…
  #       url: page?path=other/hope-studio/invite

  - tag: title
    text: æ­¤å¤„æœ‰æœç´¢ğŸ‘†

  - tag: grid
    header: æ‚¨å¯èƒ½åƒå…³æ³¨
    content:
      - text: æ‹›ç”Ÿç»†åˆ™
        color: orange
        name: Enroll
        icon: enroll
        path: /intro/enroll/

      - text: å­¦æ ¡ä»‹ç»
        color: red
        name: Description
        icon: about
        path: /intro/about/

      - text: è½¬ä¸“ä¸š
        color: blue
        name: Change Major
        icon: degree
        path: /guide/degree/change-major/

      - text: å¯å®¤
        color: mauve
        name: Dorm
        icon: dorm
        path: /guide/dorm/

      - text: é£Ÿå ‚
        color: olive
        name: Dining
        icon: dining
        path: /guide/dining/

  - tag: list
    header: ä½¿ç”¨å¿…è¯»
    content:
      - text: å°ç¨‹åºä½¿ç”¨é¡»çŸ¥
        icon: about
        url: page?path=other/about/guide

      - text: å¸¸è§é—®é¢˜åŠè§£ç­”
        icon: faq
        path: /guide/faq/

  # - tag: list
  #   header: ä»Šæ—¥è¶£é—»
  #   content:
  #     - text: ä»Šå¤© Mr.Hope é‡åˆ°äº†ä¸€ä¸ªæœ‰è¶£çš„äºº
  #       url: page?path=other/MrHope/interesting/index

  #     - text: ç°çŠ¶é™ˆè¿°
  #       desc: Mr.Hope ã®å½“å‰ç°çŠ¶
  #       url: page?path=other/MrHope/cry

  # - tag: text
  #   heading: "ä¸œæ˜Šç”µè„‘ç»´ä¿® (AD)"
  #   text: "Mr.Hope æœ‹å‹ï¼Œç›®å‰æ ¡å†…åŠå‘¨è¾¹ä»·æ ¼æœ€ä½ã€‚ç²¾ä¿®ç”µè„‘æ‰‹æœºå„ç±»é—®é¢˜(å¦‚: æ¢å±ã€ç”µæ± ã€è§£é”)ï¼Œä¼˜æƒ å‡ºå”®åç¡•åä¸ºç¬”è®°æœ¬ç”µè„‘åŠPCé…ä»¶ï¼Œï¼Œæä¾›ç³»ç»Ÿå®‰è£…ã€æ£€æµ‹ã€ä¿®å¤ï¼Œè½¯ä»¶å®‰è£…ï¼Œæ‰¿æ¥é¡¹ç›®è®¾è®¡(java,c,c++)ï¼Œæ‘„å½±ï¼Œè§†é¢‘å‰ªè¾‘ã€‚"
  #   style:
  #     color: "#888"
  #     font-size: 14px

  # - tag: advanced-list
  #   header: false
  #   content:
  #     - text: è”ç³»ä¸œæ˜Š
  #       icon: taxi
  #       openType: addFriend
  #       openId: B826FB284A0A4A75200243D5F6144B8D

  - tag: text
    heading: " "
    text: "   å¦‚æœæ‚¨è¿˜æœ‰ä»€ä¹ˆç–‘é—®ï¼Œæ¬¢è¿åŠ å…¥ in ä¸œå¸ˆå’¨è¯¢ç¾¤ (1139044856) è¿›è¡Œå’¨è¯¢ã€‚\n   å°ç¨‹åºéƒ½æ˜¯ Mr.Hope ä¸ªäººå¼€å‘ç¼–å†™ï¼Œç°å·²èŠ±è´¹ Mr.Hope è¿‘ 1800 å°æ—¶ï¼Œæ–‡å­—æ•°é‡è¶…è¿‡ 31 ä¸‡å­—ï¼ŒåŒæ—¶å°ç¨‹åºæœåŠ¡å™¨æ¯å¹´ä¼šäº§ç”Ÿå¼€é”€ã€‚å¦‚æœæ‚¨è§‰å¾—å°ç¨‹åºå¾ˆæœ‰å¸®åŠ©ï¼Œæ¬¢è¿æ‚¨ç»™äºˆæ”¯æŒã€‚"
    style:
      color: "#888"
      font-size: 14px

  - tag: advanced-list
    header: false
    content:
      - text: æ”¯æŒ Mr.Hope
        icon: contact
        openType: addFriend
        openId: 868D7B2F0C609B4285698EAB77A47BA1

      - text: åŠ å…¥ in ä¸œå¸ˆå’¨è¯¢ç¾¤
        icon: qq-group
        openType: openGroupProfile
        groupId: "1139044856"
    footer: " "
